name: Test
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
      - name: install firebase-tools
        run: npm install -g firebase-tools
      - name: install node_modules
        run: npm ci
        working-directory: ./functions
      - name: run emulator
        run: npm run emulator
        working-directory: ./functions
      - name: test
        run: npm run test
        working-directory: ./functions
      - name: Run local k6 test
        uses: grafana/k6-action@v0.2.0
        with:
        filename: ./functions/k6tests/test.js


