name: Test
on:
  workflow_dispatch
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: install firebase-tools
        run: npm install -g firebase-tools
      - name: install node_modules
        run: npm ci
        working-directory: ./functions
      - name: test
        run: npm run testci
        working-directory: ./functions

